# Generated by Django 5.2.8 on 2025-12-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0013_alter_booking_options_alter_customer_options_and_more"),
        ("cms", "0018_freeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("BOOKING_CONFIRMATION", "Booking Confirmation"),
                            (
                                "PARTY_BOOKING_CONFIRMATION",
                                "Party Booking Confirmation",
                            ),
                            ("PAYMENT_CONFIRMATION", "Payment Confirmation"),
                            ("BOOKING_REMINDER", "Booking Reminder"),
                            ("WAIVER_REMINDER", "Waiver Reminder"),
                            ("BOOKING_CANCELLED", "Booking Cancelled"),
                            ("ADMIN_NEW_BOOKING", "Admin: New Booking"),
                            ("ADMIN_CONTACT_MESSAGE", "Admin: Contact Message"),
                        ],
                        help_text="Type of email being sent",
                        max_length=50,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        help_text="Email address of recipient", max_length=254
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=255),
                ),
                (
                    "template_name",
                    models.CharField(help_text="Template file used", max_length=100),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Template variables as JSON"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if sending failed",
                        null=True,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        help_text="Azure message ID for tracking",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts made"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3, help_text="Maximum number of retries allowed"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to retry next (if failed)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When email was queued"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When email was successfully sent",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related session booking (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="bookings.booking",
                    ),
                ),
                (
                    "contact_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related contact message (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="cms.contactmessage",
                    ),
                ),
                (
                    "party_booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related party booking (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="bookings.partybooking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="emails_emai_status_0b5614_idx",
                    ),
                    models.Index(
                        fields=["email_type", "created_at"],
                        name="emails_emai_email_t_10931c_idx",
                    ),
                    models.Index(
                        fields=["recipient_email"],
                        name="emails_emai_recipie_8fd7a7_idx",
                    ),
                    models.Index(
                        fields=["next_retry_at"], name="emails_emai_next_re_983ec1_idx"
                    ),
                ],
            },
        ),
    ]
