# Generated by Django 5.2.8 on 2025-12-07 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0009_waiver_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "background_image",
                    models.ImageField(upload_to="invitation_templates/"),
                ),
                (
                    "default_title",
                    models.CharField(default="You're Invited!", max_length=255),
                ),
                (
                    "default_message",
                    models.TextField(
                        default="Come join us for a party at Ninja Inflatable Park!"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookingInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("child_name", models.CharField(blank=True, max_length=255, null=True)),
                ("party_date", models.DateField(blank=True, null=True)),
                ("party_time", models.TimeField(blank=True, null=True)),
                (
                    "venue",
                    models.CharField(default="Ninja Inflatable Park", max_length=255),
                ),
                ("custom_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation",
                        to="bookings.partybooking",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="invitations.invitationtemplate",
                    ),
                ),
            ],
        ),
    ]
