# Generated by Django 5.2.8 on 2025-12-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('PRIVATE_EVENT', 'Private Event'), ('HOLIDAY', 'Holiday'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
