# Generated by Django 5.2.8 on 2025-12-03 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_uuid"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Party organizer name", max_length=255),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "duration",
                    models.IntegerField(default=120, help_text="Duration in minutes"),
                ),
                ("adults", models.IntegerField(default=0)),
                ("kids", models.IntegerField(default=0)),
                (
                    "spectators",
                    models.IntegerField(
                        default=0, help_text="Non-participating guests"
                    ),
                ),
                (
                    "party_package",
                    models.CharField(
                        blank=True,
                        help_text="Selected party package",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, help_text="Party theme", max_length=100, null=True
                    ),
                ),
                (
                    "birthday_child_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("birthday_child_age", models.IntegerField(blank=True, null=True)),
                ("decorations", models.BooleanField(default=False)),
                ("catering", models.BooleanField(default=False)),
                ("cake", models.BooleanField(default=False)),
                ("photographer", models.BooleanField(default=False)),
                ("party_favors", models.BooleanField(default=False)),
                ("special_requests", models.TextField(blank=True, null=True)),
                ("dietary_restrictions", models.TextField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "voucher_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "waiver_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SIGNED", "Signed")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="party_bookings",
                        to="bookings.customer",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="party_bookings",
                        to="shop.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Booking",
                "verbose_name_plural": "Party Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
