# Generated by Django 5.2.8 on 2025-12-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_partybooking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partybooking",
            options={},
        ),
        migrations.RenameField(
            model_name="partybooking",
            old_name="booking_status",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="cake",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="catering",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="decorations",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="dietary_restrictions",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="party_favors",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="party_package",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="photographer",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="qr_code",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="special_requests",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="spectators",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="voucher",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="voucher_code",
        ),
        migrations.RemoveField(
            model_name="partybooking",
            name="waiver_status",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="method",
        ),
        migrations.AddField(
            model_name="partybooking",
            name="package_name",
            field=models.CharField(default="Standard", max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("STRIPE", "Stripe"),
                    ("CASH", "Cash"),
                    ("RAZORPAY", "Razorpay"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookingblock",
            name="reason",
            field=models.CharField(default="Closed", max_length=255),
        ),
        migrations.AlterField(
            model_name="bookingblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("CLOSED", "Closed"),
                    ("MAINTENANCE", "Maintenance"),
                    ("PRIVATE_EVENT", "Private Event"),
                    ("OTHER", "Other"),
                ],
                default="CLOSED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="partybooking",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="partybooking",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
