# Generated by Django 5.2.8 on 2025-12-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_partybooking_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingblock",
            name="reason",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="partybooking",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="partybooking",
            name="package_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("STRIPE", "Stripe"),
                    ("CASH", "Cash"),
                    ("RAZORPAY", "Razorpay"),
                ],
                max_length=20,
            ),
        ),
    ]
