# Generated by Django 5.2.8 on 2025-12-04 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0006_alter_bookingblock_reason_alter_partybooking_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partybooking",
            name="participants",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="waiver_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="waiver_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="waiver_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waiver",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waiver",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waiver",
            name="is_primary_signer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="waiver",
            name="participant_type",
            field=models.CharField(
                choices=[("ADULT", "Adult"), ("MINOR", "Minor")],
                default="ADULT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="waiver",
            name="party_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waivers",
                to="bookings.partybooking",
            ),
        ),
        migrations.AddField(
            model_name="waiver",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="waiver",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="waiver",
            name="version",
            field=models.CharField(default="1.0", max_length=20),
        ),
    ]
