# Generated by Django 5.2.8 on 2025-12-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_partybooking_participants_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waiver",
            name="file_url",
        ),
    ]
