# Generated by Django 5.2.8 on 2025-12-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_remove_waiver_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="waiver",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
