# Generated by Django 5.2.8 on 2025-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_waiver_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="arrived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
