# Generated by Django 5.2.8 on 2025-12-13 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_booking_arrived_booking_arrived_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyBookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("package_name", models.CharField(max_length=255)),
                ("kids", models.IntegerField(default=0)),
                ("adults", models.IntegerField(default=0)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "birthday_child_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("birthday_child_age", models.IntegerField(blank=True, null=True)),
                ("participants", models.JSONField(blank=True, null=True)),
                (
                    "original_booking_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Original booking ID if it existed",
                        null=True,
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway transaction ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount actually paid",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        help_text="Why this booking went to history (e.g., 'Payment succeeded but save failed')"
                    ),
                ),
                (
                    "restored",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this booking has been restored",
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, help_text="When the booking was restored", null=True
                    ),
                ),
                (
                    "restored_booking_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the booking created when restored",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who restored this booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_party_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Booking History",
                "verbose_name_plural": "Party Booking History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionBookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("adults", models.IntegerField(default=0)),
                ("kids", models.IntegerField(default=0)),
                ("spectators", models.IntegerField(default=0)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "voucher_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "original_booking_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Original booking ID if it existed",
                        null=True,
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway transaction ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount actually paid",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        help_text="Why this booking went to history (e.g., 'Payment succeeded but save failed')"
                    ),
                ),
                (
                    "restored",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this booking has been restored",
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, help_text="When the booking was restored", null=True
                    ),
                ),
                (
                    "restored_booking_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the booking created when restored",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who restored this booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_session_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Booking History",
                "verbose_name_plural": "Session Booking History",
                "ordering": ["-created_at"],
            },
        ),
    ]
