# Generated by Django 5.2.8 on 2025-12-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_partybookinghistory_sessionbookinghistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="partybooking",
            name="arrived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
