# Generated by Django 5.2.8 on 2025-12-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_partybooking_arrived_partybooking_arrived_at"),
        ("shop", "0002_remove_product_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="partybooking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Party Booking",
                "verbose_name_plural": "Party Bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="waiver",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Waiver",
                "verbose_name_plural": "Waivers",
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["date", "time"], name="bookings_bo_date_9ed98b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["email"], name="bookings_bo_email_2e2fb9_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["uuid"], name="bookings_bo_uuid_c3e83d_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_status"], name="bookings_bo_booking_9deb2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["payment_status"], name="bookings_bo_payment_27706e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["-created_at"], name="bookings_bo_created_7d6386_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer"], name="bookings_bo_custome_4b90f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="bookings_cu_email_bec9bd_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["-created_at"], name="bookings_cu_created_4c11c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partybooking",
            index=models.Index(
                fields=["date", "time"], name="bookings_pa_date_9b4ed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partybooking",
            index=models.Index(fields=["email"], name="bookings_pa_email_4758dc_idx"),
        ),
        migrations.AddIndex(
            model_name="partybooking",
            index=models.Index(fields=["uuid"], name="bookings_pa_uuid_2002ab_idx"),
        ),
        migrations.AddIndex(
            model_name="partybooking",
            index=models.Index(fields=["status"], name="bookings_pa_status_350108_idx"),
        ),
        migrations.AddIndex(
            model_name="partybooking",
            index=models.Index(
                fields=["-created_at"], name="bookings_pa_created_fe0d07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partybooking",
            index=models.Index(
                fields=["customer"], name="bookings_pa_custome_927cbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiver",
            index=models.Index(fields=["email"], name="bookings_wa_email_2d5a99_idx"),
        ),
        migrations.AddIndex(
            model_name="waiver",
            index=models.Index(
                fields=["booking"], name="bookings_wa_booking_47adbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiver",
            index=models.Index(
                fields=["party_booking"], name="bookings_wa_party_b_4cec18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiver",
            index=models.Index(
                fields=["customer"], name="bookings_wa_custome_201863_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiver",
            index=models.Index(
                fields=["participant_type"], name="bookings_wa_partici_802f3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waiver",
            index=models.Index(
                fields=["-created_at"], name="bookings_wa_created_7f2027_idx"
            ),
        ),
    ]
