# Generated by Django 5.2.8 on 2026-01-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_alter_booking_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("BLOCKED_DATE", "Blocked Date"),
                    ("CLOSED_TODAY", "Closed Today (Popup)"),
                    ("OPEN_TODAY", "Open Today (Holiday)"),
                    ("CLOSED", "Closed"),
                    ("MAINTENANCE", "Maintenance"),
                    ("PRIVATE_EVENT", "Private Event"),
                    ("OTHER", "Other"),
                ],
                default="BLOCKED_DATE",
                max_length=20,
            ),
        ),
    ]
