# Generated by Django 5.2.8 on 2026-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_alter_booking_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingblock",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Toggle this block on/off"
            ),
        ),
        migrations.AddField(
            model_name="bookingblock",
            name="priority",
            field=models.IntegerField(
                default=0, help_text="Higher number = higher priority for alerts"
            ),
        ),
        migrations.AlterField(
            model_name="bookingblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("BLOCKED_DATE", "Blocked Date"),
                    ("CLOSED_TODAY", "Closed Today (Popup)"),
                    ("OPEN_TODAY", "Open Today (Holiday)"),
                    ("CLOSED", "Closed"),
                    ("MAINTENANCE", "Maintenance"),
                    ("PRIVATE_EVENT", "Private Event"),
                    ("OTHER", "Other"),
                ],
                default="BLOCKED_DATE",
                max_length=20,
            ),
        ),
    ]
