# Generated by Django 5.2.8 on 2026-01-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0014_alter_bookingblock_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount paid so far",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount paid so far",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Fully Paid"),
                    ("REFUNDED", "Refunded"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Fully Paid"),
                    ("REFUNDED", "Refunded"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
