# Generated by Django 5.2.8 on 2026-01-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0015_booking_paid_amount_partybooking_paid_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(
                blank=True,
                help_text="Unique booking number (NIP-YYYYMMDD-XXXX)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="partybooking",
            name="booking_number",
            field=models.CharField(
                blank=True,
                help_text="Unique booking number (NIPARTY-YYYYMMDD-XXXX)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
