# Generated by Django 5.2.8 on 2026-01-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0016_booking_booking_number_partybooking_booking_number"),
        ("shop", "0003_add_min_hours_before_slot"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["name"], name="bookings_bo_name_562a70_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["phone"], name="bookings_bo_phone_fe5671_idx"),
        ),
        migrations.AddIndex(
            model_name="partybooking",
            index=models.Index(fields=["name"], name="bookings_pa_name_475274_idx"),
        ),
        migrations.AddIndex(
            model_name="partybooking",
            index=models.Index(fields=["phone"], name="bookings_pa_phone_c50df7_idx"),
        ),
        migrations.AddIndex(
            model_name="waiver",
            index=models.Index(fields=["name"], name="bookings_wa_name_1ff067_idx"),
        ),
    ]
