# Generated by Django 5.2.8 on 2025-12-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="STAFF", max_length=50),
        ),
    ]
