# Generated by Django 5.2.8 on 2025-12-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="party_availability",
            field=models.CharField(
                default="Thursday - Sunday",
                help_text="Party booking availability days",
                max_length=100,
            ),
        ),
    ]
