# Generated by Django 5.2.8 on 2025-12-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_globalsettings_party_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Logo name/description", max_length=255),
                ),
                (
                    "image",
                    models.ImageField(help_text="Logo image file", upload_to="logos/"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="Set as active logo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Logo",
                "verbose_name_plural": "Logos",
                "ordering": ["-created_at"],
            },
        ),
    ]
