# Generated by Django 5.2.8 on 2025-12-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BOOKING", "New Booking"),
                            ("PARTY_BOOKING", "New Party Booking"),
                            ("CONTACT_MESSAGE", "Contact Message"),
                            ("WAIVER_PENDING", "Waiver Pending"),
                            ("LOW_INVENTORY", "Low Inventory"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("SYSTEM", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("booking_id", models.IntegerField(blank=True, null=True)),
                ("party_booking_id", models.IntegerField(blank=True, null=True)),
                ("contact_message_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
