# Generated by Django 5.2.8 on 2026-01-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Manager"),
                    ("CONTENT_MANAGER", "Content Manager"),
                    ("STAFF", "Staff"),
                    ("EMPLOYEE", "Employee"),
                ],
                default="STAFF",
                max_length=50,
            ),
        ),
    ]
