# Generated by Django 5.2.8 on 2026-01-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("BOOKING_CONFIRMATION", "Booking Confirmation"),
                    ("PARTY_BOOKING_CONFIRMATION", "Party Booking Confirmation"),
                    ("PAYMENT_CONFIRMATION", "Payment Confirmation"),
                    ("BOOKING_REMINDER", "Booking Reminder"),
                    ("WAIVER_REMINDER", "Waiver Reminder"),
                    ("BOOKING_CANCELLED", "Booking Cancelled"),
                    ("ADMIN_NEW_BOOKING", "Admin: New Booking"),
                    ("ADMIN_CONTACT_MESSAGE", "Admin: Contact Message"),
                    ("WAIVER_CONFIRMATION", "Waiver Confirmation"),
                    ("MARKETING_CAMPAIGN", "Marketing Campaign"),
                    ("BIRTHDAY_MARKETING", "Birthday Automation"),
                ],
                help_text="Type of email being sent",
                max_length=50,
            ),
        ),
    ]
