# Generated by Django 5.2.8 on 2025-12-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_freeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'main_phone')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (e.g., 'Call Us')", max_length=255
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Contact value (phone, email, address, etc.)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone"),
                            ("EMAIL", "Email"),
                            ("ADDRESS", "Address"),
                            ("HOURS", "Operating Hours"),
                            ("SOCIAL", "Social Media"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name (e.g., 'Phone', 'Mail')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional link (tel:, mailto:, maps link)",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Contact Information",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="FacilityItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("icon", models.CharField(help_text="Icon name", max_length=50)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "items",
                    models.JSONField(
                        default=list, help_text="List of specific items/features"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PartyPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_participants", models.IntegerField()),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                (
                    "includes",
                    models.JSONField(default=list, help_text="List of included items"),
                ),
                (
                    "addons",
                    models.JSONField(
                        default=list, help_text="List of available add-ons"
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("popular", models.BooleanField(default=False)),
                (
                    "variant",
                    models.CharField(
                        default="accent", help_text="Color variant", max_length=20
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("SESSION", "Session"), ("PARTY", "Party")],
                        max_length=20,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Ages 1-7 Years'",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                (
                    "period_text",
                    models.CharField(
                        default="/ 60 Mins",
                        help_text="e.g., '/ 60 Mins', '/ Person'",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="List of features/inclusions"
                    ),
                ),
                ("popular", models.BooleanField(default=False)),
                (
                    "variant",
                    models.CharField(
                        default="primary",
                        help_text="Color variant: primary, secondary, accent",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["type", "order"],
            },
        ),
        migrations.CreateModel(
            name="TimelineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ValueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., 'Users', 'Shield')", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Color variant: primary, secondary, accent",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        help_text="Page identifier (e.g., 'about', 'contact')",
                        max_length=100,
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        help_text="Section identifier (e.g., 'hero', 'features')",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Call-to-action button text",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cta_link",
                    models.URLField(
                        blank=True, help_text="Call-to-action button link", null=True
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["page", "order"],
                "unique_together": {("page", "section_key")},
            },
        ),
    ]
