# Generated by Django 5.2.8 on 2025-12-04 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_contactinfo_facilityitem_partypackage_pricingplan_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FreeEntry",
        ),
        migrations.DeleteModel(
            name="StaticPage",
        ),
    ]
