# Generated by Django 5.2.8 on 2025-12-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_delete_freeentry_delete_staticpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subtitle", models.TextField()),
                (
                    "min_size",
                    models.CharField(help_text="e.g., '15+ Students'", max_length=100),
                ),
                ("icon", models.CharField(help_text="Icon name", max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_note",
                    models.CharField(help_text="e.g., 'per student'", max_length=50),
                ),
                (
                    "features",
                    models.JSONField(default=list, help_text="List of features"),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary", help_text="Color variant", max_length=20
                    ),
                ),
                ("popular", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GuidelineCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("icon", models.CharField(help_text="Icon name", max_length=50)),
                (
                    "items",
                    models.JSONField(default=list, help_text="List of guideline items"),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Guideline Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InstagramReel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("reel_url", models.URLField(help_text="Instagram reel URL")),
                ("thumbnail_url", models.URLField(help_text="Thumbnail image URL")),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("TERMS", "Terms & Conditions"),
                            ("DETAILED_RULES", "Detailed Rules"),
                            ("WAIVER", "Participant Waiver"),
                            ("PRIVACY", "Privacy Policy"),
                            ("WAIVER_TERMS", "Waiver Terms"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="Optional introduction text", null=True
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=list,
                        help_text="List of sections with title and content",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Legal Documents",
            },
        ),
        migrations.CreateModel(
            name="MenuSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., 'Pre-Plated', 'Buffet'", max_length=100
                    ),
                ),
                (
                    "items",
                    models.JSONField(default=list, help_text="List of menu items"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name", max_length=50, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="secondary", help_text="Color variant", max_length=20
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StatCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="e.g., 'Happy Jumpers'", max_length=100),
                ),
                ("value", models.CharField(help_text="e.g., '5,000+'", max_length=50)),
                (
                    "unit",
                    models.CharField(help_text="e.g., 'Happy Jumpers'", max_length=100),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., 'Users')", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Color variant: primary, secondary, accent",
                        max_length=20,
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        help_text="Page identifier: 'home' or 'about'", max_length=50
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["page", "order"],
            },
        ),
    ]
