# Generated by Django 5.2.8 on 2025-12-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_grouppackage_guidelinecategory_instagramreel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Unique page identifier (e.g., 'home', 'about')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="SEO Title", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="SEO Description", null=True
                    ),
                ),
                (
                    "keywords",
                    models.TextField(blank=True, help_text="SEO Keywords", null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
