# Generated by Django 5.2.8 on 2025-12-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="gallery",
            field=models.JSONField(
                default=list, help_text="List of additional image URLs"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="short_description",
            field=models.TextField(
                blank=True, help_text="Brief summary for list views", null=True
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly name",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(help_text="Full detailed description"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="image_url",
            field=models.URLField(help_text="Main cover image"),
        ),
    ]
