# Generated by Django 5.2.8 on 2025-12-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_activity_gallery_activity_short_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
