# Generated by Django 5.2.8 on 2025-12-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_contactmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testimonial",
        ),
    ]
