# Generated by Django 5.2.8 on 2025-12-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_delete_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField()),
                ("rating", models.IntegerField(default=5)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("VIDEO", "Video")],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
