# Generated by Django 5.2.8 on 2025-12-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_testimonial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instagramreel",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Instagram Reel",
                "verbose_name_plural": "Instagram Reels",
            },
        ),
        migrations.AlterField(
            model_name="instagramreel",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Display order (lower numbers first)"
            ),
        ),
        migrations.AlterField(
            model_name="instagramreel",
            name="title",
            field=models.CharField(help_text="Reel title/description", max_length=255),
        ),
    ]
