# Generated by Django 5.2.8 on 2025-12-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0012_alter_instagramreel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagramreel",
            name="reel_url",
            field=models.URLField(help_text="Instagram reel URL", max_length=700),
        ),
        migrations.AlterField(
            model_name="instagramreel",
            name="thumbnail_url",
            field=models.URLField(help_text="Thumbnail image URL", max_length=700),
        ),
    ]
