# Generated by Django 5.2.8 on 2025-12-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0013_alter_instagramreel_reel_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagramreel",
            name="reel_url",
            field=models.CharField(help_text="Instagram reel URL", max_length=700),
        ),
        migrations.AlterField(
            model_name="instagramreel",
            name="thumbnail_url",
            field=models.CharField(
                help_text="Thumbnail image URL (local path or external link)",
                max_length=700,
            ),
        ),
    ]
