# Generated by Django 5.2.8 on 2025-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_alter_instagramreel_reel_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="image_url",
            field=models.CharField(
                help_text="Image URL (local path or external link)", max_length=700
            ),
        ),
    ]
