# Generated by Django 5.2.8 on 2025-12-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_alter_galleryitem_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionBookingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adult_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=899,
                        help_text="Price per adult",
                        max_digits=10,
                    ),
                ),
                (
                    "adult_label",
                    models.CharField(
                        default="Ninja Warrior (7+ Years)",
                        help_text="Display label for adults",
                        max_length=100,
                    ),
                ),
                (
                    "adult_description",
                    models.CharField(
                        default="₹ 899 + GST per person",
                        help_text="Price description for adults",
                        max_length=200,
                    ),
                ),
                (
                    "kid_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        help_text="Price per kid",
                        max_digits=10,
                    ),
                ),
                (
                    "kid_label",
                    models.CharField(
                        default="Little Ninjas (1-7 Years)",
                        help_text="Display label for kids",
                        max_length=100,
                    ),
                ),
                (
                    "kid_description",
                    models.CharField(
                        default="₹ 500 + GST per person",
                        help_text="Price description for kids",
                        max_length=200,
                    ),
                ),
                (
                    "spectator_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=150,
                        help_text="Price per spectator",
                        max_digits=10,
                    ),
                ),
                (
                    "spectator_label",
                    models.CharField(
                        default="Spectators",
                        help_text="Display label for spectators",
                        max_length=100,
                    ),
                ),
                (
                    "spectator_description",
                    models.CharField(
                        default="₹ 150 + GST per person",
                        help_text="Price description for spectators",
                        max_length=200,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="GST percentage (e.g., 18 for 18%)",
                        max_digits=5,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=60, help_text="Session duration in minutes"
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(
                        default="60 Minutes",
                        help_text="Display label for duration",
                        max_length=100,
                    ),
                ),
                (
                    "duration_description",
                    models.CharField(
                        default="Standard Session",
                        help_text="Duration description",
                        max_length=200,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Session Booking Configuration",
                "verbose_name_plural": "Session Booking Configuration",
            },
        ),
    ]
