# Generated by Django 5.2.8 on 2025-12-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0016_sessionbookingconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyBookingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=1500.0,
                        help_text="Price per participant",
                        max_digits=10,
                    ),
                ),
                (
                    "participant_label",
                    models.CharField(
                        default="Participants",
                        help_text="Label for participants",
                        max_length=200,
                    ),
                ),
                (
                    "participant_description",
                    models.CharField(
                        default="₹ 1500 per person",
                        help_text="Description shown for participants",
                        max_length=500,
                    ),
                ),
                (
                    "spectator_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Price per extra spectator (after free count)",
                        max_digits=10,
                    ),
                ),
                (
                    "free_spectators",
                    models.IntegerField(
                        default=10, help_text="Number of free spectators included"
                    ),
                ),
                (
                    "spectator_label",
                    models.CharField(
                        default="Spectators",
                        help_text="Label for spectators",
                        max_length=200,
                    ),
                ),
                (
                    "spectator_description",
                    models.CharField(
                        default="First 10 free, ₹100 each after",
                        help_text="Description shown for spectators",
                        max_length=500,
                    ),
                ),
                (
                    "min_participants",
                    models.IntegerField(
                        default=10, help_text="Minimum number of participants required"
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="GST rate in percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "deposit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Deposit percentage required",
                        max_digits=5,
                    ),
                ),
                (
                    "package_inclusions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of package inclusions (e.g., ['75 mins play + 1hr party room', 'Party feast included'])",
                    ),
                ),
                (
                    "available_time_slots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of available time slots (e.g., ['12:00 PM', '2:00 PM', '4:00 PM', '6:00 PM'])",
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(
                        default="75 mins play + 1hr party room",
                        help_text="Duration/package label",
                        max_length=200,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Party Booking Configuration",
                "verbose_name_plural": "Party Booking Configuration",
            },
        ),
    ]
