# Generated by Django 5.2.8 on 2025-12-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_partybookingconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("reason", models.TextField(help_text="Reason for free entry request")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Admin notes", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Free Entry",
                "verbose_name_plural": "Free Entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
