# Generated by Django 5.2.8 on 2026-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0018_freeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttractionVideoSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "video",
                    models.FileField(max_length=500, upload_to="attraction_videos/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Attraction Video Section",
                "verbose_name_plural": "Attraction Video Sections",
                "ordering": ["-created_at"],
            },
        ),
    ]
