# Generated by Django 5.2.8 on 2026-01-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0020_alter_instagramreel_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="menusection",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Subtitle or description (e.g. 'For each participant')",
                null=True,
            ),
        ),
    ]
