# Generated by Django 5.2.8 on 2026-01-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_seed_party_food_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingCarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title/alt text",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        help_text="URL of the image (uploaded via gallery or external)",
                        max_length=700,
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pricing Carousel Image",
                "verbose_name_plural": "Pricing Carousel Images",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
