# Generated by Django 5.2.8 on 2026-01-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0023_pricingcarouselimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractionvideosection",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Poster image to show while video loads",
                null=True,
                upload_to="attraction_thumbnails/",
            ),
        ),
    ]
