# Generated by Django 5.2.8 on 2026-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0024_attractionvideosection_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractionvideosection",
            name="youtube_url",
            field=models.CharField(
                blank=True,
                help_text="YouTube URL (e.g., https://youtube.com/shorts/TKflY2nTraQ)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attractionvideosection",
            name="video",
            field=models.FileField(
                blank=True, max_length=500, upload_to="attraction_videos/"
            ),
        ),
    ]
