# Generated by Django 5.2.8 on 2026-01-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0025_add_youtube_url_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attractionvideosection",
            name="youtube_url",
            field=models.CharField(
                blank=True,
                help_text="YouTube URL (e.g., https://youtube.com/shorts/TKflY2nTraQ) - Auto-embeds",
                max_length=500,
                null=True,
            ),
        ),
    ]
