# Generated by Django 5.2.8 on 2026-01-09 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0026_trigger_azure_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attractionvideosection",
            name="youtube_url",
        ),
    ]
