# Generated by Django 5.2.8 on 2026-01-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0027_revert_youtube_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attractionvideosection",
            name="video",
            field=models.CharField(
                blank=True,
                help_text="YouTube, Vimeo, or other video URL",
                max_length=500,
                null=True,
            ),
        ),
    ]
