# Generated by Django 5.2.8 on 2026-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0028_alter_attractionvideosection_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionInformationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Ninja Inflatable Park Session Booking",
                        help_text="Main page title",
                        max_length=255,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="Booking Available from Thursday's to Sunday's",
                        help_text="Subtitle/tagline",
                        max_length=255,
                    ),
                ),
                (
                    "session_information_title",
                    models.CharField(
                        default="Session Information",
                        help_text="Title for session information section",
                        max_length=255,
                    ),
                ),
                (
                    "session_information",
                    models.TextField(
                        help_text="Session information content (supports markdown/HTML)"
                    ),
                ),
                (
                    "session_rules_title",
                    models.CharField(
                        default="Session Rules",
                        help_text="Title for session rules section",
                        max_length=255,
                    ),
                ),
                (
                    "session_rules",
                    models.TextField(
                        help_text="Session rules content (supports markdown/HTML)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one record should be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Session Information Page",
                "verbose_name_plural": "Session Information Pages",
                "ordering": ["-updated_at"],
            },
        ),
    ]
