# Generated by Django 5.2.8 on 2026-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="min_hours_before_slot",
            field=models.IntegerField(
                default=0,
                help_text="Minimum hours required between current time and booking slot. 0 = no restriction.",
            ),
        ),
    ]
