"""
Django settings for ninja_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')

def get_env_bool(name, default=False):
    return str(os.getenv(name, str(default))).lower().strip() in ['true', '1', 'yes']

def get_env_list(name, default=''):
    val = os.getenv(name, default)
    return [x.strip() for x in val.split(',') if x.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool('DEBUG', False)  # Default to False for security

# SECURITY WARNING: keep the secret key used in production secret!
if not DEBUG and not os.getenv('SECRET_KEY'):
    raise ValueError("SECRET_KEY environment variable must be set in production!")
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key-fallback')

# Azure App Service will set WEBSITE_HOSTNAME
# We allow '*' in Azure because the App Service Load Balancer handles domain verification.
# This prevents "DisallowedHost" errors from Azure's internal health probes (169.254.x.x).
ALLOWED_HOSTS = get_env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')
if 'WEBSITE_HOSTNAME' in os.environ:
    ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://ninjainflablepark-gbhwbbdna5hjgvf9.centralindia-01.azurewebsites.net',
    'https://ninjapark-frontend.azurewebsites.net',
    'https://www.ninjainflatablepark.com',
    'https://ninjainflatablepark.com',
    'https://api.ninjainflatablepark.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'django_filters',

    # Local
    'apps.core',
    'apps.bookings',
    'apps.cms',
    'apps.shop',
    'apps.invitations',
    'apps.payments',  # Payment system with mock and Razorpay gateways
    'apps.emails.apps.EmailsConfig',  # Email system - use full path to ensure signals are registered
    'apps.marketing.apps.MarketingConfig',  # Azure Email Marketing System
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Top priority for CORS
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ... existing code ...

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # Enabled to fix production CORS issues
# CORS_ALLOWED_ORIGINS = [ ... ] # Kept for reference but overridden by ALLOW_ALL

ROOT_URLCONF = 'ninja_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ninja_backend.wsgi.application'


# Upload Constraints
# Limit to 500MB as requested
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL if DB_ENGINE is set in environment, otherwise use SQLite
# Use PostgreSQL by default for production readiness
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'ninjapark_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD'),  # No fallback - fail fast if not set
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'require',  # Azure PostgreSQL requires SSL encryption
            },
        }
    }
else:
    # Default to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.core.authentication.JWTCookieAuthentication',  # Custom cookie-based JWT auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback to header-based
        'rest_framework.authentication.SessionAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Reduced from 7 days to 30 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Reduced from 30 days to 7 days
    'ROTATE_REFRESH_TOKENS': True,  # Rotate refresh tokens on use
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old tokens
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}

# REST Framework Configuration
# TEMPORARILY DISABLED - Breaks frontend which expects plain arrays
# Will re-enable after updating frontend to handle paginated responses
# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 100,  # Limit to 100 items per page to prevent memory issues
# }

SPECTACULAR_SETTINGS = {
    'TITLE': 'Ninja Park API',
    'DESCRIPTION': 'API for Ninja Inflatable Park',
    'VERSION': '1.0.0',
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5000",
    "https://ninjapark-frontend.azurewebsites.net",  # Azure frontend
    "https://www.ninjainflatablepark.com",  # Custom domain
    "https://ninjainflatablepark.com",  # Root domain
]
CSRF_TRUSTED_ORIGINS.extend(get_env_list('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:3001,http://localhost:5000'))

# Add Azure App Service domains to CSRF_TRUSTED_ORIGINS
if 'WEBSITE_HOSTNAME' in os.environ:
    CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ['WEBSITE_HOSTNAME']}")

CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_ALL_ORIGINS = True  # Disabled to allowing credentials

# Azure Storage Configuration
# FORCE ENABLE AZURE FOR MIGRATION
USE_AZURE_STORAGE = True 

if USE_AZURE_STORAGE:
    # Production: Use Azure Blob Storage
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "connection_string": os.getenv("AZURE_CONNECTION_STRING"),
                "azure_container": "media",
                "overwrite_files": False,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://ninjapark.blob.core.windows.net/media/"
else:
    # Local Development: Use Filesystem
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ====================================================
# EMAIL SYSTEM CONFIGURATION (Azure Communication Services)
# ====================================================

# Feature Flags (ALL DISABLED BY DEFAULT)
EMAIL_ENABLED = os.getenv('EMAIL_ENABLED', 'False').lower() == 'true'
EMAIL_BOOKING_ENABLED = os.getenv('EMAIL_BOOKING_ENABLED', 'False').lower() == 'true'
EMAIL_DEBUG_MODE = os.getenv('EMAIL_DEBUG_MODE', 'True').lower() == 'true'

# Azure Communication Services Credentials
AZURE_COMMUNICATION_CONNECTION_STRING = os.getenv('AZURE_COMMUNICATION_CONNECTION_STRING', '')
AZURE_EMAIL_SENDER_ADDRESS = os.getenv('AZURE_EMAIL_SENDER_ADDRESS', '')
AZURE_EMAIL_SENDER_NAME = os.getenv('AZURE_EMAIL_SENDER_NAME', 'Ninja Inflatable Park')

# Email Feature Flags
EMAIL_ENABLED = get_env_bool('EMAIL_ENABLED', True)
EMAIL_BOOKING_ENABLED = get_env_bool('EMAIL_BOOKING_ENABLED', True)
EMAIL_DEBUG_MODE = get_env_bool('EMAIL_DEBUG_MODE', False)

# Email Retry Configuration
EMAIL_MAX_RETRIES = int(os.getenv('EMAIL_MAX_RETRIES', '3'))
EMAIL_RETRY_DELAY_MINUTES = int(os.getenv('EMAIL_RETRY_DELAY_MINUTES', '1'))

# Logging
# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'django_security.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',  # Log security warnings
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'apps.payments': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps.bookings': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps.emails': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# ====================================================
# PAYMENT GATEWAY CONFIGURATION
# ====================================================

# Payment Mode: 'mock' (default, no real money) or 'razorpay' (production)
PAYMENT_MODE = os.getenv('PAYMENT_MODE', 'mock')

# Razorpay Credentials (only needed when PAYMENT_MODE='razorpay')
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')

# Payment Settings
ALLOW_PARTIAL_PAYMENTS = True  # Allow partial payments (50% deposit)
MINIMUM_DEPOSIT_PERCENTAGE = 50  # Not used when ALLOW_PARTIAL_PAYMENTS = False

# ====================================================
# SECURITY HEADERS
# ====================================================

# XSS Protection
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking Protection
X_FRAME_OPTIONS = 'DENY'

# HTTPS Enforcement (only in production)
if not DEBUG:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie Security
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# File Upload Security
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB (reduced from 500 MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB (reduced from 500 MB)

# Database Connection Pooling
if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES['default']['CONN_MAX_AGE'] = 600  # 10 minutes

