# Generated by Django 5.2.8 on 2026-01-09 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_marketingcampaign_custom_email_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                        ],
                        default="SENT",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_logs",
                        to="marketing.marketingcampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("OPEN", "Email Opened"), ("CLICK", "Link Clicked")],
                        max_length=10,
                    ),
                ),
                (
                    "event_url",
                    models.URLField(
                        blank=True,
                        help_text="URL clicked (for CLICK events)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "send_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="marketing.emailsendlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emailsendlog",
            index=models.Index(
                fields=["campaign", "status"], name="marketing_e_campaig_7e68e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsendlog",
            index=models.Index(
                fields=["recipient_email"], name="marketing_e_recipie_a7f134_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsendlog",
            index=models.Index(
                fields=["tracking_id"], name="marketing_e_trackin_5a9a7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["send_log", "event_type"], name="marketing_e_send_lo_f5e36c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailengagement",
            index=models.Index(
                fields=["created_at"], name="marketing_e_created_7af02d_idx"
            ),
        ),
    ]
