# Generated by Django 5.2.8 on 2026-01-12 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0015_booking_paid_amount_partybooking_paid_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MOCK", "Mock Gateway"), ("RAZORPAY", "Razorpay")],
                        help_text="Payment gateway provider",
                        max_length=20,
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique order ID from payment gateway",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Payment ID from gateway (set after successful payment)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount (negative for refunds)",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="CREATED",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response from payment provider",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this payment",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Session booking this payment belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "party_booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Party booking this payment belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.partybooking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "status"],
                        name="payments_pa_provide_cc7861_idx",
                    ),
                    models.Index(
                        fields=["booking", "status"],
                        name="payments_pa_booking_57d6de_idx",
                    ),
                    models.Index(
                        fields=["party_booking", "status"],
                        name="payments_pa_party_b_869921_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="payments_pa_created_3147e3_idx"
                    ),
                ],
            },
        ),
    ]
